name: Make NDK (Windows)
run-name: Make NDK-r${{inputs.version}}${{inputs.revision}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "NDK Release version:"
        default: "30"
        required: true
        type: string
      revision:
        description: "NDK Release revision:"
        required: false
        type: string

permissions:
  contents: write
  packages: read

jobs:
  make:
    uses: ./.github/workflows/make-ndk.yml
    secrets: inherit
    with:
      platform: windows
      version: ${{ inputs.version }}
      revision: ${{ inputs.revision }}
      targets: >-
        ["i686-w64-mingw32", "x86_64-w64-mingw32"]
